import "./features-report.scss";
import React, { useState } from "react";
import { Route, Redirect } from "react-router-dom";

import { AppRoute, SequencerRoute, ReportRoutes } from "@aladdin/domain-models";
import {
  MDBCol,
  MDBContainer,
  MDBIcon,
  MDBNav,
  MDBNavItem,
  MDBNavLink,
  MDBRow,
} from "mdbreact";
import { ModelTabs } from "./models/model-tabs";

import DataSamplesComparison from "./data-samples-comparison/data-samples-comparison";
import { DataSamples } from "./data-samples/data-samples";
import { useModal, SharedModal } from "@aladdin/shared/modals";
import { AladdinSearchbar } from "@aladdin/ui-kit";

export const FeaturesReport: React.FC = () => {
  const [activeItem, setAtiveItem] = useState<number>(ModelTabs.DataSample);
  const { showModal, toggleModal } = useModal();
  const toggleTabs = (tab: ModelTabs) => {
    if (activeItem !== tab) {
      setAtiveItem(tab);
    }
  };

  const viewReportModalContent = [
    {
      description:
        "Step 1: Select which reports you wish to view by selecting the appropriate data tabs.",
    },
    {
      description:
        "Step 2: Data without comparisons has many files that you can choose from (e.g., excel, scatterplots, and MaPlots). Select any of these files to view your report in.",
    },
    {
      description:
        "Step 3: Click on the 'report' icon next to the 'info' icon to get view a snapshot of your overall report analysis.",
    },
  ];
  const renderViewReportModalContent = viewReportModalContent.map(
    (content, index) => {
      return (
        <>
          <li key={index}>{content.description}</li>
          <br />
        </>
      );
    }
  );
  return (
    <div className="report-container">
      <div className="d-flex">
        <h1 className="mx-2">Report</h1>
        <a href="https://www.google.com">
          <MDBIcon icon="file-contract" size="lg" />
        </a>
        <MDBIcon
          className="d-flex align-items-center mx-2"
          icon="info-circle"
          size="lg"
          onClick={toggleModal}
        />
        <div className="global-search-container">
          <AladdinSearchbar />
        </div>
      </div>
      <p>
        This section contains results and figures generated by differential gene
        expressions and gene set enrichment analysis comparison. <br /> Click on
        one of the two tabs that corresponds to your search.
      </p>

      <MDBNav className="nav-tabs mt-5">
        <MDBNavItem>
          <MDBNavLink
            link
            to={`/${AppRoute.sequencer}/${SequencerRoute.Report}/${ReportRoutes.DataSample}`}
            active={activeItem === ModelTabs.DataSample}
            onClick={() => toggleTabs(ModelTabs.DataSample)}
            role="tab"
          >
            Data Samples
          </MDBNavLink>
        </MDBNavItem>
        <MDBNavItem>
          <MDBNavLink
            link
            to={`/${AppRoute.sequencer}/${SequencerRoute.Report}/${ReportRoutes.DataSampleWithComparison}`}
            active={activeItem === ModelTabs.DataSampleWithComparisons}
            onClick={() => toggleTabs(ModelTabs.DataSampleWithComparisons)}
            role="tab"
          >
            Data Sample W/ Comparisons
          </MDBNavLink>
        </MDBNavItem>
      </MDBNav>

      <Route
        exact
        path={`/${AppRoute.sequencer}/${SequencerRoute.Report}`}
        render={() => {
          return (
            <Redirect
              to={`/${AppRoute.sequencer}/${SequencerRoute.Report}/${ReportRoutes.DataSample}`}
            />
          );
        }}
      />

      <Route
        path={`/${AppRoute.sequencer}/${SequencerRoute.Report}/${ReportRoutes.DataSample}`}
        component={() => {
          toggleTabs(ModelTabs.DataSample);
          return <DataSamples />;
        }}
      />
      <Route
        path={`/${AppRoute.sequencer}/${SequencerRoute.Report}/${ReportRoutes.DataSampleWithComparison}`}
        component={() => {
          toggleTabs(ModelTabs.DataSampleWithComparisons);
          return <DataSamplesComparison />;
        }}
      />
      <SharedModal
        headerText="How to View Your Report"
        showModal={showModal}
        handleCloseModal={toggleModal}
      >
        <MDBContainer>
          <MDBRow>
            <MDBCol>
              <div className="report-content">
                <ul>{renderViewReportModalContent}</ul>
              </div>
            </MDBCol>
            <MDBCol className="security-image-col d-flex justify-content-center">
              Image for Modal
            </MDBCol>
          </MDBRow>
        </MDBContainer>
      </SharedModal>
    </div>
  );
};

export default FeaturesReport;
