import './security.scss';
import React, { useState } from 'react';
import {
  MDBCardText,
  MDBCol,
  MDBContainer,
  MDBIcon,
  MDBRow,
  MDBSwitch,
} from 'mdbreact';
import { SettingSwitch } from './models/setting-switch';
import { useModal, SharedModal } from '@aladdin/shared/modals';

export const Security: React.FC = () => {
  const { showModal, toggleModal } = useModal();

  const [enableSwitch, setEnableSwitch] = useState<
    Record<SettingSwitch, boolean>
  >({
    [SettingSwitch.SecurityAuthenticationSwitch]: true,
    [SettingSwitch.OTASwitch]: false,
  });

  const handleSettingSwitch = (settingSwitch: SettingSwitch) => {
    const updatedSwitch = { [settingSwitch]: !enableSwitch[settingSwitch] };
    setEnableSwitch({
      ...enableSwitch,
      ...updatedSwitch,
    });
  };
  const securityAuthenticationModalContent = [
    {
      title: 'Change Password and Step Authentication',
      description:
        'Change password or activate a two step authentication using a 2FA method. 2FA adds an additional layer of security on top of your password, requiring a second authentication at login.',
    },
    {
      title: 'Security Key Authentication',
      description:
        'Use a hardware authentication key, such as a Yubikey or Google Titan Key. Any Y2F/FIDO2 compliant device is supported. Multiple security keys can be paired to the same account.',
    },
    {
      title: 'OTP Authentication',
      description:
        'Use a One Time Password (OTP), such as the codes generated by an authenticator app (e.g., Google Authenticator).   A List of backup codes will also be available to access your account if you happen to lose or break your OTP device.',
    },
  ];
  const renderSecurityAuthenticationModalContent = securityAuthenticationModalContent.map(
    (content) => {
      return (
        <>
          <h3 key={content.title}>{content.title}</h3>
          <p key={content.title}>{content.description}</p>
        </>
      );
    }
  );
  return (
    <>
      <MDBCardText tag="h2" className="account-card-content py-3 text-left">
        <p>
          Security Key Authentication{' '}
          <MDBIcon icon="info-circle" onClick={toggleModal} />
        </p>

        <div>
          <MDBSwitch
            checked={enableSwitch.SecurityAuthenticationSwitch}
            onChange={() =>
              handleSettingSwitch(SettingSwitch.SecurityAuthenticationSwitch)
            }
          />
        </div>
      </MDBCardText>
      <MDBCardText tag="h2" className="account-card-content text-left">
        <p>
          OTA Authentication{' '}
          <MDBIcon icon="info-circle" onClick={toggleModal} />
        </p>
        <div>
          <MDBSwitch
            checked={enableSwitch.OTASwitch}
            onChange={() => handleSettingSwitch(SettingSwitch.OTASwitch)}
          />
        </div>
      </MDBCardText>
      <SharedModal
        headerText="Tips on Security Authentication"
        showModal={showModal}
        handleCloseModal={toggleModal}
      >
        <MDBContainer>
          <MDBRow>
            <MDBCol>
              <div className="authentication-content">
                {renderSecurityAuthenticationModalContent}
              </div>
            </MDBCol>
            <MDBCol className="security-image-col d-flex justify-content-center">
              Image for Modal
            </MDBCol>
          </MDBRow>
        </MDBContainer>
      </SharedModal>
    </>
  );
};

export default Security;
